### ISSUE TITLE
 Module `crypto` does not exist in the Haste module map

### ISSUE THREAD

**Issue by ZeroCool00** [sehrope/node-rand-token#11]
bundling failed: Error: Unable to resolve module `crypto` from `C:\React Project\node_modules\rand-token\index.js`:

**Comment by sehrope** [comment]
By default rand-token uses the `crypto` module as a source of randomness. That error is happening because the crypto module doesn't exist in the browser, it's only in node. For generic browser usage you'll need to specify `'math'` as the source (to use Math.random()) though note that it won't be cryptographically secure.
