### ISSUE TITLE
crypto.pseudoRandomBytes no longer exists

### ISSUE THREAD

**Issue by harshinim** [sehrope/node-rand-token#5]
I get this error with default options - crypto.pseudoRandomBytes is not a function - looks like the latest version of crypto does not have pseudoRandomBytes function anymore - can we fix it to use some other available method please?

**Comment by sehrope** [comment]
Not sure which version of node you were testing this with as the latest has `pseudoRandomBytes` as an alias for `randomBytes`. Either way, I've published a new version, v0.3.0, that retains the old behavior if `pseudoRandomBytes` is available, otherwise it uses `randomBytes`. That should handle any future removal of it from node core.
